"""
Django settings for mibbsbackend project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from dotenv import load_dotenv
import os 
from pathlib import Path


# load_dotenv()
# BREVO_API_KEY = os.getenv("BREVO_API_KEY")


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# TEMPLATES_DIRS = os.path.join(BASE_DIR,'templates')
STATIC_DIRS = os.path.join(BASE_DIR,'static')

# Load .env from BASE_DIR
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Now you can safely get your BREVO_API_KEY
BREVO_API_KEY = os.getenv("BREVO_API_KEY")

YOUTUBE_API_KEY = os.getenv("YOUTUBE_API_KEY")

YOUTUBE_CHANNEL_ID = os.getenv("YOUTUBE_CHANNEL_ID")

ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")

GITHUB_OWNER = os.getenv("GITHUB_OWNER")

GITHUB_REPO = os.getenv("GITHUB_REPO")

GITHUB_BRANCH = os.getenv("GITHUB_BRANCH")

UNSPLASH_ACCESS_KEY = os.getenv("UNSPLASH_ACCESS_KEY")


DATA_UPLOAD_MAX_MEMORY_SIZE = 25 * 1024 * 1024   # 25MB total request
FILE_UPLOAD_MAX_MEMORY_SIZE = 2 * 1024 * 1024     # 2MB in-memory threshold
MAX_FILE_SIZE = 2 * 1024 * 1024


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--_)07le$^boy4!twy%4$nu#katf51fr@4bd_5w*nncz7^w)r3e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# ALLOWED_HOSTS = ['*']
ALLOWED_HOSTS = ['93.127.199.26', 'api.mibbs.ai', 'www.api.mibbs.ai']


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
    'rest_framework',
    'simple_history',
    'rest_framework_simplejwt'
]

AUTH_USER_MODEL = 'app.Users'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        # 'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}

AUTHENTICATION_BACKENDS = [
    'app.authentication_backend.EmailOrPhoneBackend', # ⬅ update to your correct path
    'django.contrib.auth.backends.ModelBackend',
]



MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]


REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ]
}


# CORS_ORIGIN_ALLOW_ALL = True
# CORS_ORIGIN_WHITELIST = [
#     # "http://localhost:5000",
#     "https://mibbs.ai"
# ]



CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    # "http://localhost:8080",
    # "http://localhost:5173",
    # "http://localhost:5174",
    "https://mibbs.ai",
    "https://intalks.in",
    "https://grofesion.com",
    "https://magsmen.com"
]


CSRF_TRUSTED_ORIGINS = [
    # "http://localhost:8080",
    # "http://localhost:5173",
    # "http://localhost:5174",
    "https://mibbs.ai",
    "https://intalks.in",
    "https://grofesion.com",
    "https://magsmen.com"
]


ROOT_URLCONF = 'mibbsbackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mibbsbackend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


STATIC_URL = 'static/'
MEDIA_URL = 'media/'
UPLOAD_URL = 'upload/'

if DEBUG == True:
   STATICFILES_DIRS = (STATIC_DIRS,)
else:
    STATIC_ROOT = STATIC_DIRS

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
UPLOAD_ROOT = os.path.join(BASE_DIR,'upload')


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.zoho.in'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'hr@magsmen.com'          # your Gmail address
EMAIL_HOST_PASSWORD = 'w17cv3WijRZ0'         # Gmail App Password (not your real password)
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# magsmenconnect@gmail.com  old gmail 

# lhln yivw ywva ewiy  app password this is old password

# srvg zyzz tfqb xgvs new app password




# Change 'UTC' to your specific region
TIME_ZONE = 'Asia/Kolkata'  

# Keep this True to handle daylight savings and standard practices
USE_TZ = True