# Generated by Django 5.2.4 on 2025-10-06 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('brand_stage', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=6)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('state', models.CharField(blank=True, max_length=128)),
                ('industry', models.CharField(blank=True, max_length=128)),
                ('years_in_business', models.IntegerField(blank=True, null=True)),
                ('digital_maturity', models.CharField(blank=True, max_length=100)),
                ('primary_goals', models.JSONField(blank=True, default=list)),
                ('monthly_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('marketing_spend_band', models.CharField(blank=True, max_length=50)),
                ('exact_marketing_spend', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('positioning', models.CharField(blank=True, max_length=100)),
                ('competitor_notes', models.TextField(blank=True)),
                ('industry_details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
