# Generated by Django 5.2.4 on 2025-10-08 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_assessment_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
