# Generated by Django 5.2.4 on 2025-10-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
