# Generated by Django 5.2.4 on 2025-11-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_assessment_annual_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='annual_budget',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='monthly_budget',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
