# Generated by Django 5.2.4 on 2025-11-24 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_assessment_annual_budget_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percentage', models.FloatField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.assessment')),
            ],
        ),
    ]
