# Generated by Django 5.2.4 on 2025-11-24 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_budgetallocation_channelfocus'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetallocation',
            name='percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='budgetallocation',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_allocation_set', to='app.assessment'),
        ),
        migrations.AlterField(
            model_name='channelfocus',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_focus_set', to='app.assessment'),
        ),
        migrations.AlterField(
            model_name='channelfocus',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
