# Generated by Django 5.2.4 on 2025-11-24 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_budgetallocation_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetallocation',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.assessment'),
        ),
        migrations.AlterField(
            model_name='channelfocus',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.assessment'),
        ),
    ]
