# Generated by Django 5.2.4 on 2025-11-24 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_budgetallocation_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='piechart_str',
            field=models.TextField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='budgetallocation',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_allocation_set', to='app.assessment'),
        ),
        migrations.AlterField(
            model_name='channelfocus',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_focus_set', to='app.assessment'),
        ),
        migrations.CreateModel(
            name='PieChartEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.FloatField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pie_chart_entries', to='app.assessment')),
            ],
        ),
    ]
