# Generated by Django 5.2.4 on 2025-11-24 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_assessment_piechart_str_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='budget_allocations',
        ),
        migrations.DeleteModel(
            name='BudgetAllocation',
        ),
    ]
