# Generated by Django 5.2.4 on 2025-11-24 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_assessment_budget_allocations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='channel_focuses',
        ),
        migrations.AddField(
            model_name='assessment',
            name='barchart_data',
            field=models.TextField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='BarChartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bar_chart_data', to='app.assessment')),
            ],
        ),
        migrations.DeleteModel(
            name='ChannelFocus',
        ),
    ]
