# Generated by Django 5.2.4 on 2025-11-25 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_assessment_channel_focuses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='budget_allocations',
            field=models.TextField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_allocation_set', to='app.assessment')),
            ],
        ),
    ]
