# Generated by Django 5.2.4 on 2025-11-25 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_assessment_budget_allocations_budgetallocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='budget_allocations',
        ),
        migrations.DeleteModel(
            name='BudgetAllocation',
        ),
    ]
