# Generated by Django 5.2.8 on 2025-12-03 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_assessment_budget_allocations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='barchart_data',
        ),
        migrations.DeleteModel(
            name='BarChartData',
        ),
    ]
