# Generated by Django 5.2.8 on 2025-12-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_assessment_barchart_data_delete_barchartdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusers',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalusers',
            name='reset_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='reset_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
