# Generated by Django 5.2.8 on 2025-12-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_historicalusers_reset_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='annual_budget',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='monthly_budget',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='piechart_str',
            field=models.CharField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='historicalusers',
            name='reset_token',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='reset_token',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
