# Generated by Django 5.2.8 on 2025-12-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_assessment_annual_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusers',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
