# Generated by Django 5.2.8 on 2025-12-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_historicalusers_username_alter_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalusers',
            name='username',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
