# Generated by Django 5.2.8 on 2025-12-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_assessment_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='exact_marketing_spend',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='monthly_revenue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='piechartentry',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
