# Generated by Django 5.2.8 on 2025-12-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_assessment_exact_marketing_spend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
