# Generated by Django 5.2.8 on 2025-12-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_assessment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusers',
            name='login_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='historicalusers',
            name='login_otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='login_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='login_otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
