# Generated by Django 6.0 on 2026-01-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_historicalusers_login_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='months_in_business',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
