# Generated by Django 6.0 on 2026-01-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_assessment_months_in_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intaklksstatspupdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtubestats', models.CharField(blank=True, max_length=255, null=True)),
                ('instagramstats', models.CharField(blank=True, max_length=255, null=True)),
                ('communitygrowthstats', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='intaklks_stats/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('guestname', models.CharField(blank=True, max_length=255, null=True)),
                ('podcasttime', models.CharField(blank=True, max_length=50, null=True)),
                ('podcastdate', models.DateField(blank=True, null=True)),
                ('podcastnumber', models.IntegerField(blank=True, null=True)),
                ('youtubelink', models.URLField(blank=True, max_length=500, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
