# Generated by Django 6.0 on 2026-01-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_intaklksstatspupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='intaklksstatspupdate',
            name='podcastviews',
            field=models.IntegerField(default=0),
        ),
    ]
