# Generated by Django 6.0 on 2026-03-25 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_intaklksstatspupdate_podcastviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='piechart_str',
            field=models.CharField(blank=True, default=list, max_length=5000, null=True),
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('business_name', models.CharField(max_length=200)),
                ('business_stage', models.CharField(max_length=50)),
                ('has_website', models.BooleanField(default=False)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('pincode', models.CharField(max_length=6)),
                ('locality', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=200)),
                ('business_type', models.CharField(max_length=50)),
                ('product_business_type', models.CharField(blank=True, max_length=50, null=True)),
                ('starting_budget', models.CharField(blank=True, max_length=100, null=True)),
                ('business_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('help_needed', models.JSONField(blank=True, null=True)),
                ('years_in_business', models.CharField(blank=True, max_length=50, null=True)),
                ('business_challenges', models.JSONField(blank=True, null=True)),
                ('digital_scaling_level', models.CharField(blank=True, max_length=100, null=True)),
                ('digital_platforms', models.JSONField(blank=True, null=True)),
                ('digital_activities', models.JSONField(blank=True, null=True)),
                ('roi_percentage', models.CharField(blank=True, max_length=20, null=True)),
                ('monthly_revenue', models.CharField(blank=True, max_length=100, null=True)),
                ('marketing_budget_range', models.CharField(blank=True, max_length=100, null=True)),
                ('brand_objectives', models.JSONField(blank=True, null=True)),
                ('monthly_budget', models.IntegerField(default=0)),
                ('annual_budget', models.IntegerField(default=0)),
                ('pie_chart_data', models.JSONField(blank=True, null=True)),
                ('channel_focuses', models.JSONField(blank=True, null=True)),
                ('budget_allocations', models.JSONField(blank=True, null=True)),
                ('bar_chart_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
