# Generated by Django 6.0 on 2026-03-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_assessment_piechart_str_questionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='business_mode',
            field=models.JSONField(null=True),
        ),
    ]
