# Generated by Django 6.0 on 2026-03-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_questionnaire_business_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExistingBusinessQuestionnaire',
            fields=[
            ],
            options={
                'verbose_name': 'Existing Business',
                'verbose_name_plural': 'Existing Businesses',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.questionnaire',),
        ),
        migrations.CreateModel(
            name='NewBusinessQuestionnaire',
            fields=[
            ],
            options={
                'verbose_name': 'New Business',
                'verbose_name_plural': 'New Businesses',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.questionnaire',),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='business_path',
            field=models.CharField(blank=True, choices=[('NEW', 'New Business'), ('EXISTING', 'Existing Business')], max_length=20, null=True),
        ),
    ]
