# Generated by Django 6.0 on 2026-03-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_existingbusinessquestionnaire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='annual_budget',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='bar_chart_data',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='budget_allocations',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='channel_focuses',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='monthly_budget',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='pie_chart_data',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='user',
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='business_mode',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
