# Generated by Django 6.0 on 2026-03-26 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_remove_questionnaire_annual_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='annual_budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='bar_chart_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='budget_allocations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='channel_focuses',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='monthly_budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='pie_chart_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='business_mode',
            field=models.JSONField(null=True),
        ),
    ]
