# Generated by Django 6.0 on 2026-03-26 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_questionnaire_annual_budget_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExistingBusinessQuestionnaire',
        ),
        migrations.DeleteModel(
            name='NewBusinessQuestionnaire',
        ),
        migrations.CreateModel(
            name='ExistingBusinessQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('business_name', models.CharField(max_length=200)),
                ('business_stage', models.CharField(max_length=50)),
                ('has_website', models.BooleanField(default=False)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('pincode', models.CharField(max_length=10)),
                ('locality', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('business_type', models.CharField(max_length=50)),
                ('product_business_type', models.CharField(blank=True, max_length=50, null=True)),
                ('years_in_business', models.CharField(max_length=100)),
                ('business_challenges', models.JSONField(default=list)),
                ('digital_scaling_level', models.CharField(max_length=100)),
                ('digital_platforms', models.JSONField(default=list)),
                ('digital_activities', models.JSONField(default=list)),
                ('roi_percentage', models.CharField(max_length=20)),
                ('monthly_revenue', models.CharField(max_length=100)),
                ('marketing_budget_range', models.CharField(max_length=100)),
                ('brand_objectives', models.JSONField(default=list)),
                ('monthly_budget', models.IntegerField()),
                ('annual_budget', models.IntegerField()),
                ('pie_chart_data', models.JSONField(default=list)),
                ('channel_focuses', models.JSONField(default=list)),
                ('budget_allocations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewBusinessQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('business_name', models.CharField(max_length=200)),
                ('business_stage', models.CharField(max_length=50)),
                ('has_website', models.BooleanField(default=False)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('pincode', models.CharField(max_length=10)),
                ('locality', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('business_type', models.CharField(max_length=50)),
                ('product_business_type', models.CharField(blank=True, max_length=50, null=True)),
                ('starting_budget', models.CharField(max_length=100)),
                ('business_mode', models.JSONField(default=list)),
                ('help_needed', models.JSONField(default=list)),
                ('annual_budget', models.IntegerField()),
                ('pie_chart_data', models.JSONField(default=list)),
                ('channel_focuses', models.JSONField(default=list)),
                ('budget_allocations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Questionnaire',
        ),
    ]
