# Generated by Django 6.0 on 2026-03-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_delete_existingbusinessquestionnaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newbusinessquestionnaire',
            name='monthly_budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='existingbusinessquestionnaire',
            name='annual_budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='existingbusinessquestionnaire',
            name='monthly_budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='existingbusinessquestionnaire',
            name='roi_percentage',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newbusinessquestionnaire',
            name='annual_budget',
            field=models.IntegerField(default=0),
        ),
    ]
