# Generated by Django 6.0 on 2026-03-28 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_newbusinessquestionnaire_monthly_budget_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='existingbusinessquestionnaire',
            name='budget_allocations',
        ),
        migrations.RemoveField(
            model_name='existingbusinessquestionnaire',
            name='channel_focuses',
        ),
        migrations.RemoveField(
            model_name='existingbusinessquestionnaire',
            name='pie_chart_data',
        ),
        migrations.RemoveField(
            model_name='newbusinessquestionnaire',
            name='budget_allocations',
        ),
        migrations.RemoveField(
            model_name='newbusinessquestionnaire',
            name='channel_focuses',
        ),
        migrations.RemoveField(
            model_name='newbusinessquestionnaire',
            name='pie_chart_data',
        ),
    ]
