# Generated by Django 6.0 on 2026-03-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_remove_existingbusinessquestionnaire_budget_allocations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existingbusinessquestionnaire',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newbusinessquestionnaire',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
