# Generated by Django 6.0 on 2026-03-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_existingbusinessquestionnaire_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='existingbusinessquestionnaire',
            name='budget_allocations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='existingbusinessquestionnaire',
            name='channel_focuses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='existingbusinessquestionnaire',
            name='pie_chart_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='newbusinessquestionnaire',
            name='budget_allocations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='newbusinessquestionnaire',
            name='channel_focuses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='newbusinessquestionnaire',
            name='pie_chart_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='existingbusinessquestionnaire',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='existingbusinessquestionnaire',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='existingbusinessquestionnaire',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newbusinessquestionnaire',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newbusinessquestionnaire',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='newbusinessquestionnaire',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
