# Generated by Django 6.0 on 2026-04-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_existingbusinessquestionnaire_budget_allocations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('doj', models.DateField()),
                ('role', models.CharField(max_length=200)),
                ('division', models.CharField(max_length=200)),
                ('office', models.CharField(max_length=200)),
                ('self_intro', models.TextField()),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('father_name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('emerg_name', models.CharField(max_length=200)),
                ('emerg_phone', models.CharField(max_length=20)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('qualification', models.CharField(max_length=200)),
                ('acc_name', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=200)),
                ('acc_no', models.CharField(max_length=100)),
                ('ifsc', models.CharField(max_length=20)),
                ('branch', models.CharField(blank=True, max_length=200, null=True)),
                ('ref1_name', models.CharField(max_length=200)),
                ('ref1_desg', models.CharField(max_length=200)),
                ('ref1_org', models.CharField(max_length=200)),
                ('ref1_contact', models.CharField(max_length=200)),
                ('ref2_name', models.CharField(max_length=200)),
                ('ref2_desg', models.CharField(max_length=200)),
                ('ref2_org', models.CharField(max_length=200)),
                ('ref2_contact', models.CharField(max_length=200)),
                ('aadhaar_card', models.FileField(upload_to='documents/aadhaar/')),
                ('pan_card', models.FileField(upload_to='documents/pan/')),
                ('photo', models.ImageField(upload_to='documents/photo/')),
                ('tenth_certificate', models.FileField(upload_to='documents/10th/')),
                ('inter_certificate', models.FileField(upload_to='documents/12th/')),
                ('degree_certificate', models.FileField(upload_to='documents/degree/')),
                ('college_id', models.FileField(blank=True, null=True, upload_to='documents/college_id/')),
                ('noc_letter', models.FileField(blank=True, null=True, upload_to='documents/noc/')),
                ('offer_accepted', models.BooleanField(default=False)),
                ('nda_accepted', models.BooleanField(default=False)),
                ('handbook_sections', models.TextField(blank=True)),
                ('signature', models.CharField(max_length=200)),
                ('sign_date', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
