# Generated by Django 6.0 on 2026-04-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_employeeonboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeonboarding',
            name='relieving_letter',
            field=models.FileField(blank=True, null=True, upload_to='documents/relieving/'),
        ),
        migrations.AddField(
            model_name='employeeonboarding',
            name='salary_proof',
            field=models.FileField(blank=True, null=True, upload_to='documents/salary/'),
        ),
    ]
