# Generated by Django 6.0 on 2026-04-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_employeeonboarding_relieving_letter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EODReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('date_iso', models.DateField()),
                ('weekday', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_hours', models.CharField(max_length=50)),
                ('tasks_count', models.IntegerField()),
                ('min_tasks', models.IntegerField()),
                ('met_minimum', models.CharField(max_length=10)),
                ('tasks_done', models.IntegerField()),
                ('tasks_partial', models.IntegerField()),
                ('tasks_carried', models.IntegerField()),
                ('tasks_blocked', models.IntegerField()),
                ('tasks_text', models.TextField()),
                ('tasks_json', models.JSONField()),
                ('no_meetings', models.CharField(max_length=10)),
                ('meetings_count', models.IntegerField()),
                ('meetings_text', models.TextField()),
                ('meetings_json', models.JSONField()),
                ('deliverables', models.TextField()),
                ('has_blocker', models.CharField(max_length=10)),
                ('blocker_text', models.TextField(blank=True, null=True)),
                ('tomorrow_plan', models.TextField(blank=True, null=True)),
                ('mood_score', models.IntegerField()),
                ('mood_label', models.CharField(max_length=50)),
                ('mood_emoji', models.CharField(max_length=10)),
                ('general_note', models.TextField(blank=True, null=True)),
                ('submitted_at', models.CharField(max_length=100)),
                ('hr_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
