# Generated by Django 6.0 on 2026-08-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_eodreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('employee_id', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=150)),
                ('manager', models.CharField(max_length=150)),
                ('last_working_day', models.DateField(blank=True, null=True)),
                ('notice_period', models.CharField(max_length=150)),
                ('reason', models.CharField(max_length=150)),
                ('reason_detail', models.TextField(blank=True, null=True)),
                ('agreement_accepted', models.BooleanField(default=False)),
                ('handover_items', models.TextField(blank=True)),
                ('assets_returned', models.JSONField(blank=True, default=dict)),
                ('clearance_declared', models.JSONField(blank=True, default=dict)),
                ('it_cleared', models.BooleanField(default=False)),
                ('finance_cleared', models.BooleanField(default=False)),
                ('hr_cleared', models.BooleanField(default=False)),
                ('manager_cleared', models.BooleanField(default=False)),
                ('ratings', models.JSONField(blank=True, default=dict)),
                ('like_most', models.TextField(blank=True, null=True)),
                ('improve', models.TextField(blank=True, null=True)),
                ('recommend', models.CharField(blank=True, max_length=20)),
                ('rejoin', models.CharField(blank=True, max_length=20)),
                ('signature', models.CharField(max_length=150)),
                ('sign_date', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('cleared', 'Fully Cleared'), ('settled', 'Settled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee Exit Request',
                'verbose_name_plural': 'Employee Exit Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
