# Generated by Django 6.0 on 2026-10-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_employeeexit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='employeeexit',
            name='designation',
            field=models.CharField(choices=[('Brand Strategy Intern', 'Brand Strategy Intern'), ('Business Development Intern', 'Business Development Intern'), ('Content & Digital Intern', 'Content & Digital Intern'), ('Design Intern', 'Design Intern'), ('Research Intern', 'Research Intern'), ('Management Trainee', 'Management Trainee'), ('HR Intern', 'HR Intern'), ('Web Developer Intern', 'Web Developer Intern'), ('Business Associate', 'Business Associate'), ('Strategy Associate', 'Strategy Associate'), ('Operations Associate', 'Operations Associate'), ('Digital Associate', 'Digital Associate'), ('Senior Business Development', 'Senior Business Development'), ('Lead Strategist', 'Lead Strategist'), ('Head of Operations', 'Head of Operations'), ('HR', 'HR'), ('Junior Web Developer', 'Junior Web Developer'), ('Senior Web Developer', 'Senior Web Developer'), ('Client Strategy & Growth', 'Client Strategy & Growth')], max_length=150),
        ),
        migrations.CreateModel(
            name='ClientOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('is_submitted', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('services', models.ManyToManyField(related_name='client_onboardings', to='app.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
