# Generated by Django 6.0 on 2026-10-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_service_alter_employeeexit_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientonboarding',
            name='anticipated_duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientonboarding',
            name='areas_of_sensitivity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientonboarding',
            name='client_primary_contact_designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientonboarding',
            name='client_primary_contact_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='clientonboarding',
            name='commencement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientonboarding',
            name='discovery_session_conducted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientonboarding',
            name='discovery_session_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientonboarding',
            name='engagement_reference_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientonboarding',
            name='engagement_stage',
            field=models.CharField(choices=[('Pre-Proposal Exploration', 'Pre-Proposal Exploration'), ('Proposal Stage', 'Proposal Stage'), ('Engagement Confirmed', 'Engagement Confirmed'), ('Active Delivery', 'Active Delivery'), ('Post-Engagement', 'Post-Engagement')], default='Engagement Confirmed', max_length=50),
        ),
        migrations.AddField(
            model_name='clientonboarding',
            name='industry_sector',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='clientonboarding',
            name='magsmen_engagement_lead_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='clientonboarding',
            name='magsmen_engagement_lead_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='clientonboarding',
            name='special_confidentiality_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
