# Generated by Django 6.0 on 2026-10-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_clientonboarding_anticipated_duration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientonboarding',
            options={},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.RenameField(
            model_name='clientonboarding',
            old_name='discovery_session_conducted',
            new_name='agreement_accepted',
        ),
        migrations.RenameField(
            model_name='clientonboarding',
            old_name='anticipated_duration',
            new_name='cin_no',
        ),
        migrations.RenameField(
            model_name='clientonboarding',
            old_name='client_primary_contact_designation',
            new_name='entity_type',
        ),
        migrations.RenameField(
            model_name='clientonboarding',
            old_name='engagement_reference_no',
            new_name='gst_no',
        ),
        migrations.RemoveField(
            model_name='clientonboarding',
            name='areas_of_sensitivity',
        ),
        migrations.RemoveField(
            model_name='clientonboarding',
            name='commencement_date',
        ),
        migrations.RemoveField(
            model_name='clientonboarding',
            name='discovery_session_date',
        ),
        migrations.RemoveField(
            model_name='clientonboarding',
            name='engagement_stage',
        ),
        migrations.RemoveField(
            model_name='clientonboarding',
            name='industry_sector',
        ),
        migrations.RemoveField(
            model_name='clientonboarding',
            name='is_submitted',
        ),
        migrations.RemoveField(
            model_name='clientonboarding',
            name='magsmen_engagement_lead_email',
        ),
        migrations.RemoveField(
            model_name='clientonboarding',
            name='magsmen_engagement_lead_name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='service',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='clientonboarding',
            name='nda_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientonboarding',
            name='pan_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientonboarding',
            name='client_primary_contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientonboarding',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clientonboarding',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='clientonboarding',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clientonboarding',
            name='services',
            field=models.ManyToManyField(related_name='onboarded_clients', to='app.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
